# Generated by Django 2.0.9 on 2018-12-28 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0002_auto_20181228_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bucket', to=settings.AUTH_USER_MODEL),
        ),
    ]
