# Generated by Django 2.0.9 on 2019-01-18 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0003_auto_20181228_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='complted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to=settings.AUTH_USER_MODEL),
        ),
    ]
