# Generated by Django 2.0.9 on 2019-01-18 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0004_auto_20190118_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucket',
            old_name='complted',
            new_name='completed',
        ),
    ]
